In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

# mulai dari index 1 berenti sebelum index 5
print(arr[1:5])

# mulai dari index 4 berenti sampai index habis atau ujung
print(arr[4:])

[2 3 4 5]
[5 6 7]


In [3]:
# Negative Slicing

arr = np.array([1,2,3,4,5,6,7])

# Mulai dari index -3 (5), berenti sebelum index -1
print(arr[-3:-1])

[5 6]


In [5]:
# Step
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

# [start : stop : step]
# Mulai dari index 1 -> nilai 2
# Lompat 2 langkah (step) -> index 3 -> nilai 4
# lompat lagi 2 langkah -> index 5, tapi stop di 5 (tidak ikut dan lanjut)

# Jadi yang diambil index 1 dan 3 = [2,4]



[2 4]
[1 3 5 7]


In [6]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

# Mulai dari index 0 -> nilai 1
# Stop 0 artinya terus sampai akhir
# lompat 2 langkah terus menerus sampai akhir
# index 0 -> index 2 -> index 4 -> index 6 = [1 3 5 7]

[1 3 5 7]


In [7]:
# Slicing 2D arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

# Mulai di array 1 ->  [6, 7, 8, 9, 10]
# Mulai di index ke 1 berenti sebelum index 4 -> [7 8 9]

[7 8 9]


In [9]:
arr = np.array([# 0, 1, 2 , 3 ,4
                [1, 2, 3, 4, 5], # index baris 0
                [6, 7, 8, 9, 10] # index baris 1
                ])

print(arr[0:2, 2])

# [baris, kolom]
# [0:2] -> mengambil baris mulai dari baris 0 sampai sebelum dua -> index baris 0 dan 1
# [0:2, 2] ->  ,2 berarti mengamkil kolom ke 2 -> 3 & 8

[3 8]


In [10]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]
               ])

print(arr[0:2, 1:4])
# Mengambil baris [0:2] mulai dari 0 berenti sebelum 2 - > baris 0 & 1
# Mengambil kolom [1:4] mulai dari index 1 berenti sebelum index 4
# index 0 -> [2 3 4]
# index 1 -> [7 8 9]

[[2 3 4]
 [7 8 9]]
