In [1]:
import numpy as np

# Tipe data Integer
arr= np.array([1,2,3,4])

print(arr.dtype)

int64


In [2]:
# Tipe data string
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [3]:
arr = np.array([1,2,3,4], dtype='S') # tipe data array dipaksa menjadi string byte (b)

print(arr)
print(arr.dtype) 

# S1 -> S string , 1 -> panjang karakter

[b'1' b'2' b'3' b'4']
|S1


In [4]:
arr = np.array([1,2,3,4], dtype='i4') # Tipe data array dipaksa menjadi integer
# i4 -> i (integer), 4 (4 byte)

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [ ]:
# Yang tidak bisa di convert
# arr = np.array(['a', '2', '3'], dtype='i')


In [7]:
# Convert tipe data dari array yang ada

# Mengubah tipe data float menjadi integer menggunakan 'i'
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
arr = np.array([1.1, 2.1, 3.1])

# Mengubah tipe data float menjadi integer menggunakan 'int'
newarr = arr.astype('int')

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [10]:
arr  = np.array([1,0,3])

# Mengubah tipe data integer menjadi boolean
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool
