In [4]:
# NUMPY COPY
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [5]:
# NUMPY VIEW
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] =31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [7]:
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
