In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)

print(newarr)

#Reshape from 1-D to 2-D

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,3,2)

print(newarr)

#Reshape drom 1-D to 3-D

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
#Return copy or view

arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [9]:
arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2,-1)

print(newarr)

# convert 1D array dengan 8 element menjadi 3D array dengan 2x2 element

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
arr = np.array([[1,2,3],[4,5,6]])

newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
