In [2]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [6]:
# join 2D dengan axis 1

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 3 5 6]
 [4 5 6 7 8]]


In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
