In [1]:
import numpy

# array dalam numpy
arr = numpy.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [2]:
# nama object array dalam numpy disebut ndarray
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
# 0-D array
arr = numpy.array(41)
print(arr)

41


In [4]:
#1-D array
arr = numpy.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [9]:
#2-D array
arr = numpy.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
#3-D array
arr = numpy.array([[[1,2,3],[4,5,6]],
                    [[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# cek dimension
import numpy as np

a = np.array(41)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])


print (a.ndim)
print (b.ndim)
print (c.ndim)
print (d.ndim)

0
1
2
3
